### ISSUE TITLE
Use prefixes to simplify RDF output

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-artifact-server#39]
Currently the RDF output uses full URIs everywhere, making the triples hard to read, e.g.,

    <https://repo.staging.metadatacenter.net/template-instances/f3e067c6-34d6-4901-adf1-a6c6b36b1be2> <http://purl.org/pav/lastUpdatedOn> "2017-03-20T11:52:38-0700"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

If we used prefixes we could simplify this to:

    tinst:f3e067c6-34d6-4901-adf1-a6c6b36b1be2 pav:lastUpdatedOn "2017-03-20T11:52:38-0700"^^xsd:dateTime .

We could define prefixes for xsd, schema, pav, the CEDAR repo itself and its subtypes, and so on.

Not sure how it easy it will be, however, to inject these prefixes into the current RDF generation engine.

**Comment by willrett** [comment]
client side RDF engine is this:  https://github.com/digitalbazaar/jsonld.js

**Comment by martinjoconnor** [comment]
Oh - so we are not using the server side call to generate the RDF?

Perhaps @johardi can take a quick look to see if this can be done easily or requires a lot of work.

**Comment by willrett** [comment]
The client needs to keep the RDF up-to-date as the user edits the instance. This would result in too many server calls, so we went with the client-side approach for the document preview.

**Comment by martinjoconnor** [comment]
Subsumed by metadatacenter/cedar-project#850
